# Generated by Django 4.0 on 2021-12-17 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('medallas', models.IntegerField()),
                ('batallas', models.IntegerField(default=0)),
                ('fechaRegistro', models.DateField(default=datetime.datetime(2021, 12, 17, 0, 12, 48, 44173))),
            ],
        ),
    ]
