# Generated by Django 4.0 on 2021-12-17 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0003_entrenador_nombre_alter_entrenador_medallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='numeroPokemones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='batallas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='medallas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
