# Generated by Django 4.0 on 2021-12-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0003_alter_pokemones_nombre'),
        ('entrenador', '0004_entrenador_numeropokemones_alter_entrenador_batallas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenadorPokemones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.entrenador')),
                ('pokemones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemones.pokemones')),
            ],
        ),
    ]
