# Generated by Django 4.0 on 2021-12-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0003_alter_pokemones_nombre'),
        ('entrenador', '0005_entrenadorpokemones'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrenadorpokemones',
            unique_together={('entrenador', 'pokemones')},
        ),
    ]
