# Generated by Django 4.0 on 2021-12-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenador', '0007_remove_entrenador_numeropokemones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='fechaRegistro',
            field=models.CharField(default='', max_length=100),
        ),
    ]
