# Generated by Django 4.0 on 2021-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0008_pokemonesdefault'),
        ('entrenador', '0008_alter_entrenador_fecharegistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artificial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('dificultad', models.PositiveSmallIntegerField(default=1)),
                ('imagen', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameModel(
            old_name='EntrenadorPokemones',
            new_name='EntrenadorArticialPokemones',
        ),
    ]
