# Generated by Django 4.0 on 2021-12-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0008_pokemonesdefault'),
        ('entrenador', '0010_alter_entrenadorarticialpokemones_entrenador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrenadorarticialpokemones',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entrenadorarticialpokemones',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemones.pokemonesdefault'),
        ),
        migrations.AlterField(
            model_name='entrenadorarticialpokemones',
            name='entrenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrenador.artificial'),
        ),
        migrations.AlterUniqueTogether(
            name='entrenadorarticialpokemones',
            unique_together={('entrenador', 'pokemon')},
        ),
        migrations.RemoveField(
            model_name='entrenadorarticialpokemones',
            name='pokemones',
        ),
    ]
