# Generated by Django 4.0 on 2021-12-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0008_pokemonesdefault'),
        ('entrenador', '0011_alter_entrenadorarticialpokemones_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenadorarticialpokemones',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenador.artificial'),
        ),
        migrations.AlterField(
            model_name='entrenadorarticialpokemones',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemones.pokemonesdefault'),
        ),
    ]
