# Generated by Django 4.0 on 2021-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('imagen', models.IntegerField(default=0)),
            ],
        ),
    ]
