# Generated by Django 4.0 on 2021-12-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemones',
            name='icono',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='imagen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
