# Generated by Django 4.0 on 2021-12-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0003_alter_pokemones_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemones',
            name='moviminetoCuatro',
            field=models.CharField(default='{"Ataque":"Generico","Danio":"25"}', max_length=200),
        ),
        migrations.AddField(
            model_name='pokemones',
            name='moviminetoDos',
            field=models.CharField(default='{"Ataque":"Generico","Danio":"25"}', max_length=200),
        ),
        migrations.AddField(
            model_name='pokemones',
            name='moviminetoTres',
            field=models.CharField(default='{"Ataque":"Generico","Danio":"25"}', max_length=200),
        ),
        migrations.AddField(
            model_name='pokemones',
            name='moviminetoUno',
            field=models.CharField(default='{"Ataque":"Generico","Danio":"25"}', max_length=200),
        ),
    ]
