# Generated by Django 4.0 on 2021-12-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0004_pokemones_moviminetocuatro_pokemones_moviminetodos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemones',
            name='moviminetoCuatro',
            field=models.CharField(default='Generico=25', max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='moviminetoDos',
            field=models.CharField(default='Generico=25', max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='moviminetoTres',
            field=models.CharField(default='Generico=25', max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemones',
            name='moviminetoUno',
            field=models.CharField(default='Generico=25', max_length=200),
        ),
    ]
