# Generated by Django 4.0 on 2021-12-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0005_alter_pokemones_moviminetocuatro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemones',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
