# Generated by Django 4.0 on 2021-12-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0006_alter_pokemones_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemones',
            name='entrenador',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
