# Generated by Django 4.0 on 2021-12-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemones', '0007_pokemones_entrenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonesDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('icono', models.CharField(default='', max_length=100)),
                ('imagen', models.CharField(default='', max_length=100)),
                ('moviminetoUno', models.CharField(default='Generico=25', max_length=200)),
                ('moviminetoDos', models.CharField(default='Generico=25', max_length=200)),
                ('moviminetoTres', models.CharField(default='Generico=25', max_length=200)),
                ('moviminetoCuatro', models.CharField(default='Generico=25', max_length=200)),
                ('entrenador', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
